/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capapresentacionsac;

import CapaPresentacionSAC.InterfacesPrincipales.Configuracion;
import CapaPresentacionSAC.InterfacesPrincipales.Contribuyentes;
import CapaPresentacionSAC.InterfacesSecundarias.Cantones;
import CapaPresentacionSAC.InterfacesSecundarias.Provincias;
import capapresentacionsac.interfacesprincipales.EmisionParcial;
import capapresentacionsac.interfacesprincipales.FORMULARIOEXONERACION;
import capapresentacionsac.interfacesprincipales.GESTIONUSUARIO;
import capapresentacionsac.interfacesprincipales.GESTIONZONA;
import capapresentacionsac.interfacesprincipales.INGRESOCIUDADANOS;
import capapresentacionsac.interfacesprincipales.MANZANA;
import capapresentacionsac.interfacesprincipales.Predios;
import capapresentacionsac.interfacesprincipales.VentanaDeRecaudacionRural;
import capapresentacionsac.interfacesprincipales.frmRptEMISIONES;
import capapresentacionsac.interfacessecundarias.ACCEBILIDADDERIESGO;
import capapresentacionsac.interfacessecundarias.ACCESOYVIAS;
import capapresentacionsac.interfacessecundarias.CALIDADDESUELO;
import capapresentacionsac.interfacessecundarias.DRENAJE;
import capapresentacionsac.interfacessecundarias.EROSION;
import capapresentacionsac.interfacessecundarias.FORMAPREDIO;
import capapresentacionsac.interfacessecundarias.PROBLACIONESCERCANAS;
import capapresentacionsac.interfacessecundarias.Parroquias;
import capapresentacionsac.interfacessecundarias.SECTOR;
import capapresentacionsac.interfacessecundarias.SERVICIOSBASICOS;
import capapresentacionsac.interfacessecundarias.SITIOS;
import capapresentacionsac.interfacessecundarias.SUPERFICIES;
import capapresentacionsac.interfacessecundarias.TIPORIESGO;
import capapresentacionsac.interfacessecundarias.TOPOGRAFICOS;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Pamela
 */

public class AvaluosCatastros extends javax.swing.JFrame implements Runnable{
    String hora, minutos, segundos;
    Thread hilo;
    /**
     * Creates new form AvaluosCatastros
     */
    public AvaluosCatastros() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/avaluo.png")).getImage());
        this.setExtendedState(MAXIMIZED_BOTH);
        txtFecha.setText(fecha());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true); 
        //initComponents();
        //setLocationRelativeTo(this);
        setTitle("Sistema de Avalúos y Catastros");
        
    }
    public void run(){
        Thread current = Thread.currentThread();
        while(current == hilo){
            hora();
            txtHora.setText(hora+":"+minutos+":"+segundos);
        }
    }
    
    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaActual = new Date();
        calendario.setTime(horaActual);
        hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }  
    
    public static String fecha(){
        Date fecha=new Date();
        SimpleDateFormat formatofecha=new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        provincias = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        cantones = new javax.swing.JMenuItem();
        parroquias = new javax.swing.JMenuItem();
        ciudadanos = new javax.swing.JMenuItem();
        dat_precios_can = new javax.swing.JMenuItem();
        dat_productos = new javax.swing.JMenuItem();
        dat_dest_eco = new javax.swing.JMenuItem();
        dat_catastrales = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        ing_dat_ficha = new javax.swing.JMenuItem();
        mod_fic_cats = new javax.swing.JMenuItem();
        valora_predios = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        titulo_pre_nor = new javax.swing.JMenuItem();
        titulo_pre_exe = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        reg_cat = new javax.swing.JMenuItem();
        tit_imp_cero = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        config = new javax.swing.JMenuItem();
        users = new javax.swing.JMenuItem();
        asig_permisos = new javax.swing.JMenuItem();
        resp_info = new javax.swing.JMenuItem();
        aper_nuevoanio = new javax.swing.JMenuItem();
        conf_pass = new javax.swing.JMenuItem();
        acerca_de = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        emision = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        recaudacion = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Avalúos y Catastros");
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fecha:");

        txtFecha.setText("dd/mm/aa");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Hora:");

        txtHora.setText("00:00:00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1064, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHora)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        provincias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/catastro.png"))); // NOI18N
        provincias.setText("DATOS GENERALES");
        provincias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem33.setText("PROVINCIAS");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        provincias.add(jMenuItem33);

        cantones.setText("CANTONES");
        cantones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonesActionPerformed(evt);
            }
        });
        provincias.add(cantones);

        parroquias.setText("PARROQUIAS");
        parroquias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parroquiasActionPerformed(evt);
            }
        });
        provincias.add(parroquias);

        ciudadanos.setText("CIUDADANOS");
        ciudadanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadanosActionPerformed(evt);
            }
        });
        provincias.add(ciudadanos);

        dat_precios_can.setText("DATOS DE PRECIOS DE TERRENOS POR CANTÓN");
        provincias.add(dat_precios_can);

        dat_productos.setText("DATOS DE PRODUCTOS Y PLANTACIONES");
        provincias.add(dat_productos);

        dat_dest_eco.setText("DATOS DE DESTINOS ECONÓMICOS");
        provincias.add(dat_dest_eco);

        dat_catastrales.setText("DATOS CATASTRALES");

        jMenuItem11.setText("SECTORES");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        dat_catastrales.add(jMenuItem11);

        jMenuItem12.setText("POLÍGONOS");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        dat_catastrales.add(jMenuItem12);

        jMenuItem13.setText("SITIOS");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        dat_catastrales.add(jMenuItem13);

        jMenuItem14.setText("ZONAS");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        dat_catastrales.add(jMenuItem14);

        provincias.add(dat_catastrales);

        ing_dat_ficha.setText("INGRESO DE DATOS DE FICHA PREDIAL");
        ing_dat_ficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ing_dat_fichaActionPerformed(evt);
            }
        });
        provincias.add(ing_dat_ficha);

        mod_fic_cats.setText("MODIFICACIÓN DE FICHA CATASTRAL");
        provincias.add(mod_fic_cats);

        valora_predios.setText("VALORACIÓN DE PREDIOS RURALES");

        jMenuItem15.setText("PLANO DE VALORES");
        valora_predios.add(jMenuItem15);

        jMenuItem16.setText("TASA DE INTERÉS");
        valora_predios.add(jMenuItem16);

        jMenuItem17.setText("RUBROS");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        valora_predios.add(jMenuItem17);

        provincias.add(valora_predios);

        titulo_pre_nor.setText("TÍTULO DE PREDIO NORMAL");
        provincias.add(titulo_pre_nor);

        titulo_pre_exe.setText("TÍTULO DE PREDIO EXENTO");
        provincias.add(titulo_pre_exe);

        jMenuBar2.add(provincias);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/predios.png"))); // NOI18N
        jMenu1.setText("INFORMES PREDIALES");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        reg_cat.setText("REGISTRO CATASTRAL");
        reg_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_catActionPerformed(evt);
            }
        });
        jMenu1.add(reg_cat);

        tit_imp_cero.setText("TÍTULO CON IMPORTE CERO");
        jMenu1.add(tit_imp_cero);

        jMenuItem1.setText("RECAUDACIÓN DIARIA");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("RECAUDACIÓN MENSUAL");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("BALANCE FICHAS/PREDIOS PAGADOS Y PENDIENTES");
        jMenu1.add(jMenuItem3);

        jMenuBar2.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configu.png"))); // NOI18N
        jMenu2.setText("PROCESOS ESPECIALES");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        config.setText("CONFIGURACIÓN");
        config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configActionPerformed(evt);
            }
        });
        jMenu2.add(config);

        users.setText("USUARIOS");
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });
        jMenu2.add(users);

        asig_permisos.setText("ASIGNACIÓN DE PERMISOS");
        jMenu2.add(asig_permisos);

        resp_info.setText("RESPALDOS DE INFORMACIÓN");
        jMenu2.add(resp_info);

        aper_nuevoanio.setText("APERTURA DE UN NUEVO AÑO");
        jMenu2.add(aper_nuevoanio);

        conf_pass.setText("CAMBIAR CONTRASEÑA");
        jMenu2.add(conf_pass);

        acerca_de.setText("ACERCA DE...");
        jMenu2.add(acerca_de);

        jMenuBar2.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/indicadores.png"))); // NOI18N
        jMenu3.setText("CUADRO ELEMENTOS VALORIZABLES");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem19.setText("FORMA DEL PREDIO");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem20.setText("POBLACIONES CERCANAS");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem20);

        jMenuItem21.setText("TOPOGRÁFICOS");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem21);

        jMenuItem22.setText("ACCESIBILIDAD AL RIEGO");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem22);

        jMenuItem23.setText("TIPO DE RIESGOS");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem23);

        jMenuItem24.setText("ACCESO Y VÍAS DE COMUNICACIÓN");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem24);

        jMenuItem25.setText("SERVICIOS BÁSICOS");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem25);

        jMenuItem26.setText("EROSIÓN");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem26);

        jMenuItem27.setText("DRENAJE");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem27);

        jMenuItem28.setText("SUPERFICIE");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem28);

        jMenuBar2.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rent.png"))); // NOI18N
        jMenu4.setText("RECAUDACIÓN");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        emision.setText("EMISIÓN");

        jMenuItem4.setText("PARCIAL");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        emision.add(jMenuItem4);

        jMenuItem5.setText("GENERAL");
        emision.add(jMenuItem5);

        jMenuItem6.setText("REPORTE");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        emision.add(jMenuItem6);

        jMenu4.add(emision);

        recaudacion.setText("RECAUDACIÓN");
        recaudacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recaudacionActionPerformed(evt);
            }
        });
        jMenu4.add(recaudacion);

        jMenuBar2.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proceso.png"))); // NOI18N
        jMenu5.setText("EXONERACIÓN");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem7.setText("EXONERACIÓN");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("RECTIFICAR PROPIETARIOS");
        jMenu5.add(jMenuItem8);

        jMenuBar2.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenu6.setText("REPORTES");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem9.setText("CIUDADANO");
        jMenu6.add(jMenuItem9);

        jMenuItem10.setText("PARROQUIAS");
        jMenu6.add(jMenuItem10);

        jMenuItem18.setText("USUARIOS");
        jMenu6.add(jMenuItem18);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        // TODO add your handling code here:
        Provincias obj = new Provincias();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void cantonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonesActionPerformed
        // TODO add your handling code here:
        Cantones obj = new Cantones();
        obj.setVisible(true);
    }//GEN-LAST:event_cantonesActionPerformed

    private void ing_dat_fichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ing_dat_fichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ing_dat_fichaActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void ciudadanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadanosActionPerformed
        // TODO add your handling code here:
        INGRESOCIUDADANOS obj = new INGRESOCIUDADANOS();
        obj.setVisible(true);
    }//GEN-LAST:event_ciudadanosActionPerformed

    private void parroquiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parroquiasActionPerformed
        // TODO add your handling code here:
        Parroquias obj = new Parroquias();
        obj.setVisible(true);
    }//GEN-LAST:event_parroquiasActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        SECTOR obj = new SECTOR();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        MANZANA obj = new MANZANA();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        SITIOS obj = new SITIOS();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        GESTIONZONA obj = new GESTIONZONA();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void reg_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_catActionPerformed
        // TODO add your handling code here:
        Predios obj = new Predios();
        obj.setVisible(true);
    }//GEN-LAST:event_reg_catActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        // TODO add your handling code here:
        GESTIONUSUARIO obj = new GESTIONUSUARIO();
        obj.setVisible(true);
    }//GEN-LAST:event_usersActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        EmisionParcial obj = new EmisionParcial();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        frmRptEMISIONES obj = new frmRptEMISIONES();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void recaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recaudacionActionPerformed
        // TODO add your handling code here:
        VentanaDeRecaudacionRural obj = new VentanaDeRecaudacionRural();
        obj.setVisible(true);
    }//GEN-LAST:event_recaudacionActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        FORMULARIOEXONERACION obj = new FORMULARIOEXONERACION();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        FORMAPREDIO obj = new FORMAPREDIO();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        PROBLACIONESCERCANAS obj = new PROBLACIONESCERCANAS();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        TOPOGRAFICOS obj = new TOPOGRAFICOS();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        TIPORIESGO obj = new TIPORIESGO();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        ACCESOYVIAS obj = new ACCESOYVIAS();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
        SERVICIOSBASICOS obj = new SERVICIOSBASICOS();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
        EROSION obj = new EROSION();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        DRENAJE obj = new DRENAJE();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        SUPERFICIES obj = new SUPERFICIES();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configActionPerformed
        // TODO add your handling code here:
        Configuracion obj = new Configuracion();
        obj.setVisible(true);
    }//GEN-LAST:event_configActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaluosCatastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaluosCatastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaluosCatastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaluosCatastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaluosCatastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acerca_de;
    private javax.swing.JMenuItem aper_nuevoanio;
    private javax.swing.JMenuItem asig_permisos;
    private javax.swing.JMenuItem cantones;
    private javax.swing.JMenuItem ciudadanos;
    private javax.swing.JMenuItem conf_pass;
    private javax.swing.JMenuItem config;
    private javax.swing.JMenu dat_catastrales;
    private javax.swing.JMenuItem dat_dest_eco;
    private javax.swing.JMenuItem dat_precios_can;
    private javax.swing.JMenuItem dat_productos;
    private javax.swing.JMenu emision;
    private javax.swing.JMenuItem ing_dat_ficha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mod_fic_cats;
    private javax.swing.JMenuItem parroquias;
    private javax.swing.JMenu provincias;
    private javax.swing.JMenuItem recaudacion;
    private javax.swing.JMenuItem reg_cat;
    private javax.swing.JMenuItem resp_info;
    private javax.swing.JMenuItem tit_imp_cero;
    private javax.swing.JMenuItem titulo_pre_exe;
    private javax.swing.JMenuItem titulo_pre_nor;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtHora;
    private javax.swing.JMenuItem users;
    private javax.swing.JMenu valora_predios;
    // End of variables declaration//GEN-END:variables

    
}
